name: Telegram Bot

on:
  workflow_dispatch:
  push:
    paths:
      - 'bot.py'
      - '.github/workflows/bot.yml'

jobs:
  run-bot:
    runs-on: ubuntu-latest
    timeout-minutes: 290
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - run: pip install python-telegram-bot

      - run: python bot.py
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          GAME_URL: https://cheshmha-ro-man.onrender.com
